spring.profiles: local

spring:
  application:
    name: mafia_api
  datasource:
    url: "jdbc:mysql://localhost:3306/mafia_api?useSSL=false&serverTimezone=America/New_York"
    username: "root"

flyway:
  url: jdbc:mysql://localhost:3306/mafia_api
  schemas: mafia_api
  user: "root"